skyrimRoot: F:\Steam\steamapps\common\Skyrim Special Edition
buildDir: E:\Github\skymp\build
pluginsTxtPath: C:\Users\fante\AppData\Local\Skyrim Special Edition\Plugins.txt
skseLoaderPath: F:\Steam\steamapps\common\Skyrim Special Edition
