export enum UiMenu {
  Barter = 'BarterMenu',
  Book = 'Book Menu',
  Console = 'Console',
  ConsoleNativeUI = 'Console Native UI Menu',
  Container = 'ContainerMenu',
  Crafting = 'Crafting Menu',
  Credits = 'Credits Menu',
  Cursor = 'Cursor Menu',
  Debug = 'Debug Text Menu',
  Dialogue = 'Dialogue Menu',
  Fader = 'Fader Menu',
  Favorites = 'FavoritesMenu',
  Gift = 'GiftMenu',
  HUD = 'HUD Menu',
  Inventory = 'InventoryMenu',
  Journal = 'Journal Menu',
  Kinect = 'Kinect Menu',
  LevelUp = 'LevelUp Menu',
  Loading = 'Loading Menu',
  Main = 'Main Menu',
  Lockpicking = 'Lockpicking Menu',
  Magic = 'MagicMenu',
  Map = 'MapMenu',
  MessageBox = 'MessageBoxMenu',
  Mist = 'Mist Menu',
  OverlayInteraction = 'Overlay Interaction Menu',
  Overlay = 'Overlay Menu',
  Quantity = 'Quantity Menu',
  RaceSex = 'RaceSex Menu',
  Sleep = 'Sleep/Wait Menu',
  Stats = 'StatsMenu',
  TitleSequence = 'TitleSequence Menu',
  Top = 'Top Menu',
  Training = 'Training Menu',
  Tutorial = 'Tutorial Menu',
  Tween = 'TweenMenu',
}

export const badMenus: UiMenu[] = [
  UiMenu.Barter,
  UiMenu.Book,
  UiMenu.Container,
  UiMenu.Crafting,
  UiMenu.Gift,
  UiMenu.Inventory,
  UiMenu.Journal,
  UiMenu.Lockpicking,
  UiMenu.Loading,
  UiMenu.Map,
  UiMenu.RaceSex,
  UiMenu.Stats,
  UiMenu.Tween,
  UiMenu.Console,
  UiMenu.Main,
];
