export enum FormType {
  kFormType_None,
  kFormType_TES4,
  kFormType_Group,
  kFormType_GMST,
  kFormType_Keyword,
  kFormType_LocationRef,
  kFormType_Action,
  kFormType_TextureSet,
  kFormType_MenuIcon,
  kFormType_Global,
  kFormType_Class,
  kFormType_Faction,
  kFormType_HeadPart,
  kFormType_Eyes,
  kFormType_Race,
  kFormType_Sound,
  kFormType_AcousticSpace,
  kFormType_Skill,
  kFormType_EffectSetting,
  kFormType_Script,
  kFormType_LandTexture,
  kFormType_Enchantment,
  kFormType_Spell,
  kFormType_ScrollItem,
  kFormType_Activator,
  kFormType_TalkingActivator,
  kFormType_Armor,
  kFormType_Book,
  kFormType_Container,
  kFormType_Door,
  kFormType_Ingredient,
  kFormType_Light,
  kFormType_Misc,
  kFormType_Apparatus,
  kFormType_Static,
  kFormType_StaticCollection,
  kFormType_MovableStatic,
  kFormType_Grass,
  kFormType_Tree,
  kFormType_Flora,
  kFormType_Furniture,
  kFormType_Weapon,
  kFormType_Ammo,
  kFormType_NPC,
  kFormType_LeveledCharacter,
  kFormType_Key,
  kFormType_Potion,
  kFormType_IdleMarker,
  kFormType_Note,
  kFormType_ConstructibleObject,
  kFormType_Projectile,
  kFormType_Hazard,
  kFormType_SoulGem,
  kFormType_LeveledItem,
  kFormType_Weather,
  kFormType_Climate,
  kFormType_SPGD,
  kFormType_ReferenceEffect,
  kFormType_Region,
  kFormType_NAVI,
  kFormType_Cell,
  kFormType_Reference,
  kFormType_Character,
  kFormType_Missile,
  kFormType_Arrow,
  kFormType_Grenade,
  kFormType_BeamProj,
  kFormType_FlameProj,
  kFormType_ConeProj,
  kFormType_BarrierProj,
  kFormType_PHZD,
  kFormType_WorldSpace,
  kFormType_Land,
  kFormType_NAVM,
  kFormType_TLOD,
  kFormType_Topic,
  kFormType_TopicInfo,
  kFormType_Quest,
  kFormType_Idle,
  kFormType_Package,
  kFormType_CombatStyle,
  kFormType_LoadScreen,
  kFormType_LeveledSpell,
  kFormType_ANIO,
  kFormType_Water,
  kFormType_EffectShader,
  kFormType_TOFT,
  kFormType_Explosion,
  kFormType_Debris,
  kFormType_ImageSpace,
  kFormType_ImageSpaceMod,
  kFormType_List,
  kFormType_Perk,
  kFormType_BodyPartData,
  kFormType_AddonNode,
  kFormType_ActorValueInfo,
  kFormType_CameraShot,
  kFormType_CameraPath,
  kFormType_VoiceType,
  kFormType_MaterialType,
  kFormType_ImpactData,
  kFormType_ImpactDataSet,
  kFormType_ARMA,
  kFormType_EncounterZone,
  kFormType_Location,
  kFormType_Message,
  kFormType_Ragdoll,
  kFormType_DOBJ,
  kFormType_LightingTemplate,
  kFormType_MusicType,
  kFormType_Footstep,
  kFormType_FootstepSet,
  kFormType_StoryBranchNode,
  kFormType_StoryQuestNode,
  kFormType_StoryEventNode,
  kFormType_DialogueBranch,
  kFormType_MusicTrack,
  kFormType_DLVW,
  kFormType_WordOfPower,
  kFormType_Shout,
  kFormType_EquipSlot,
  kFormType_Relationship,
  kFormType_Scene,
  kFormType_AssociationType,
  kFormType_Outfit,
  kFormType_Art,
  kFormType_Material,
  kFormType_MovementType,
  kFormType_SoundDescriptor,
  kFormType_DualCastData,
  kFormType_SoundCategory,
  kFormType_SoundOutput,
  kFormType_CollisionLayer,
  kFormType_ColorForm,
  kFormType_ReverbParam,
  kFormType_LensFlare,
  kFormType_Unk88,
  kFormType_VolumetricLighting,
  kFormType_Unk8A,
  kFormType_Alias,
  kFormType_ReferenceAlias,
  kFormType_LocationAlias,
  kFormType_ActiveMagicEffect,

  kFormType_Max = kFormType_VolumetricLighting,
}

export const formType: Record<string, number> = {
  NONE: FormType.kFormType_None,
  TES4: FormType.kFormType_TES4,
  GRUP: FormType.kFormType_Group,
  GMST: FormType.kFormType_GMST,
  KYWD: FormType.kFormType_Keyword,
  LCRT: FormType.kFormType_LocationRef,
  AACT: FormType.kFormType_Action,
  TXST: FormType.kFormType_TextureSet,
  MICN: FormType.kFormType_MenuIcon,
  GLOB: FormType.kFormType_Global,
  CLAS: FormType.kFormType_Class,
  FACT: FormType.kFormType_Faction,
  HDPT: FormType.kFormType_HeadPart,
  EYES: FormType.kFormType_Eyes,
  RACE: FormType.kFormType_Race,
  SOUN: FormType.kFormType_Sound,
  ASPC: FormType.kFormType_AcousticSpace,
  SKIL: FormType.kFormType_Skill,
  MGEF: FormType.kFormType_EffectSetting,
  SCPT: FormType.kFormType_Script,
  LTEX: FormType.kFormType_LandTexture,
  ENCH: FormType.kFormType_Enchantment,
  SPEL: FormType.kFormType_Spell,
  SCRL: FormType.kFormType_ScrollItem,
  ACTI: FormType.kFormType_Activator,
  TACT: FormType.kFormType_TalkingActivator,
  ARMO: FormType.kFormType_Armor,
  BOOK: FormType.kFormType_Book,
  CONT: FormType.kFormType_Container,
  DOOR: FormType.kFormType_Door,
  INGR: FormType.kFormType_Ingredient,
  LIGH: FormType.kFormType_Light,
  MISC: FormType.kFormType_Misc,
  APPA: FormType.kFormType_Apparatus,
  STAT: FormType.kFormType_Static,
  SCOL: FormType.kFormType_StaticCollection,
  MSTT: FormType.kFormType_MovableStatic,
  GRAS: FormType.kFormType_Grass,
  TREE: FormType.kFormType_Tree,
  FLOR: FormType.kFormType_Flora,
  FURN: FormType.kFormType_Furniture,
  WEAP: FormType.kFormType_Weapon,
  AMMO: FormType.kFormType_Ammo,
  NPC_: FormType.kFormType_NPC,
  LVLN: FormType.kFormType_LeveledCharacter,
  KEYM: FormType.kFormType_Key,
  ALCH: FormType.kFormType_Potion,
  IDLM: FormType.kFormType_IdleMarker,
  NOTE: FormType.kFormType_Note,
  COBJ: FormType.kFormType_ConstructibleObject,
  PROJ: FormType.kFormType_Projectile,
  HAZD: FormType.kFormType_Hazard,
  SLGM: FormType.kFormType_SoulGem,
  LVLI: FormType.kFormType_LeveledItem,
  WTHR: FormType.kFormType_Weather,
  CLMT: FormType.kFormType_Climate,
  SPGD: FormType.kFormType_SPGD,
  RFCT: FormType.kFormType_ReferenceEffect,
  REGN: FormType.kFormType_Region,
  NAVI: FormType.kFormType_NAVI,
  CELL: FormType.kFormType_Cell,
  REFR: FormType.kFormType_Reference,
  ACHR: FormType.kFormType_Character,
  PMIS: FormType.kFormType_Missile,
  PARW: FormType.kFormType_Arrow,
  PGRE: FormType.kFormType_Grenade,
  PBEA: FormType.kFormType_BeamProj,
  PFLA: FormType.kFormType_FlameProj,
  PCON: FormType.kFormType_ConeProj,
  PBAR: FormType.kFormType_BarrierProj,
  PHZD: FormType.kFormType_PHZD,
  WRLD: FormType.kFormType_WorldSpace,
  LAND: FormType.kFormType_Land,
  NAVM: FormType.kFormType_NAVM,
  TLOD: FormType.kFormType_TLOD,
  DIAL: FormType.kFormType_Topic,
  INFO: FormType.kFormType_TopicInfo,
  QUST: FormType.kFormType_Quest,
  IDLE: FormType.kFormType_Idle,
  PACK: FormType.kFormType_Package,
  CSTY: FormType.kFormType_CombatStyle,
  LSCR: FormType.kFormType_LoadScreen,
  LVSP: FormType.kFormType_LeveledSpell,
  ANIO: FormType.kFormType_ANIO,
  WATR: FormType.kFormType_Water,
  EFSH: FormType.kFormType_EffectShader,
  TOFT: FormType.kFormType_TOFT,
  EXPL: FormType.kFormType_Explosion,
  DEBR: FormType.kFormType_Debris,
  IMGS: FormType.kFormType_ImageSpace,
  IMAD: FormType.kFormType_ImageSpaceMod,
  FLST: FormType.kFormType_List,
  PERK: FormType.kFormType_Perk,
  BPTD: FormType.kFormType_BodyPartData,
  ADDN: FormType.kFormType_AddonNode,
  AVIF: FormType.kFormType_ActorValueInfo,
  CAMS: FormType.kFormType_CameraShot,
  CPTH: FormType.kFormType_CameraPath,
  VTYP: FormType.kFormType_VoiceType,
  MATT: FormType.kFormType_MaterialType,
  IPCT: FormType.kFormType_ImpactData,
  IPDS: FormType.kFormType_ImpactDataSet,
  ARMA: FormType.kFormType_ARMA,
  ECZN: FormType.kFormType_EncounterZone,
  LCTN: FormType.kFormType_Location,
  MESH: FormType.kFormType_Message,
  RGDL: FormType.kFormType_Ragdoll,
  DOBJ: FormType.kFormType_DOBJ,
  LGTM: FormType.kFormType_LightingTemplate,
  MUSC: FormType.kFormType_MusicType,
  FSTP: FormType.kFormType_Footstep,
  FSTS: FormType.kFormType_FootstepSet,
  SMBN: FormType.kFormType_StoryBranchNode,
  SMQN: FormType.kFormType_StoryQuestNode,
  SMEN: FormType.kFormType_StoryEventNode,
  DLBR: FormType.kFormType_DialogueBranch,
  MUST: FormType.kFormType_MusicTrack,
  DLVW: FormType.kFormType_DLVW,
  WOOP: FormType.kFormType_WordOfPower,
  SHOU: FormType.kFormType_Shout,
  EQUP: FormType.kFormType_EquipSlot,
  RELA: FormType.kFormType_Relationship,
  SCEN: FormType.kFormType_Scene,
  ASTP: FormType.kFormType_AssociationType,
  OTFT: FormType.kFormType_Outfit,
  ARTO: FormType.kFormType_Art,
  MATO: FormType.kFormType_Material,
  MOVT: FormType.kFormType_MovementType,
  SNDR: FormType.kFormType_SoundDescriptor,
  DUAL: FormType.kFormType_DualCastData,
  SNCT: FormType.kFormType_SoundCategory,
  SOPM: FormType.kFormType_SoundOutput,
  COLL: FormType.kFormType_CollisionLayer,
  CLFM: FormType.kFormType_ColorForm,
  REVB: FormType.kFormType_ReverbParam,
  BGSBaseAlias: FormType.kFormType_Alias,
  BGSRefAlias: FormType.kFormType_ReferenceAlias,
  BGSLocAlias: FormType.kFormType_LocationAlias,
  ActiveMagicEffect: FormType.kFormType_ActiveMagicEffect,
};