#include "AnimVariableMasterGraphIndexes.h"
#include "AnimationVariablesForMasterBehavior.h"

AnimVariableMasterGraphIndexes AnimVariableMasterGraphIndexes::CreateDefault()
{
  std::array<uint32_t, 14> intVarIndexes = { kiRightHandEquipped,
                                             kiLeftHandEquipped,
                                             ki1HMState,
                                             kiState,
                                             kiLeftHandType,
                                             kiRightHandType,
                                             kiSyncIdleLocomotion,
                                             kiSyncForwardState,
                                             kiSyncTurnState,
                                             kiIsInSneak,
                                             kiWantBlock,
                                             kiRegularAttack,
                                             ktestint,
                                             kcurrentDefaultState };

  std::array<uint32_t, 13> floatVarIndexes = {
    kTurnDelta, kDirection,     kSpeedSampled,   kweapAdj, kSpeed,
    kCastBlend, kPitchOffset,   kSpeedDamped,    kPitch,   kVelocityZ,
    k1stPRot,   k1stPRotDamped, kCastBlendDamped
  };

  std::array<uint32_t, 60> boolVarIndexes = { kbEquipOk,
                                              kbMotionDriven,
                                              kIsBeastRace,
                                              kIsSneaking,
                                              kIsBleedingOut,
                                              kIsCastingDual,
                                              kIs1HM,
                                              kIsCastingRight,
                                              kIsCastingLeft,
                                              kIsBlockHit,
                                              kIsPlayer,
                                              kIsNPC,
                                              kbIsSynced,
                                              kbVoiceReady,
                                              kbWantCastLeft,
                                              kbWantCastRight,
                                              kbWantCastVoice,
                                              kb1HM_MLh_attack,
                                              kb1HMCombat,
                                              kbAnimationDriven,
                                              kbCastReady,
                                              kIsAttacking,
                                              kbAllowRotation,
                                              kbMagicDraw,
                                              kbMLh_Ready,
                                              kbMRh_Ready,
                                              kbInMoveState,
                                              kbSprintOK,
                                              kbIdlePlaying,
                                              kbIsDialogueExpressive,
                                              kbAnimObjectLoaded,
                                              kbEquipUnequip,
                                              kbAttached,
                                              kbIsH2HSolo,
                                              kbHeadTracking,
                                              kbIsRiding,
                                              kbTalkable,
                                              kbRitualSpellActive,
                                              kbInJumpState,
                                              kbHeadTrackSpine,
                                              kbLeftHandAttack,
                                              kbIsInMT,
                                              kbHumanoidFootIKEnable,
                                              kbHumanoidFootIKDisable,
                                              kbStaggerPlayerOverride,
                                              kbNoStagger,
                                              kbIsStaffLeftCasting,
                                              kbPerkShieldCharge,
                                              kbPerkQuickShot,
                                              kIsBlocking,
                                              kIsBashing,
                                              kIsStaggering,
                                              kIsRecoiling,
                                              kIsEquipping,
                                              kIsUnequipping,
                                              kisInFurniture,
                                              kbNeutralState,
                                              kbBowDrawn,
                                              kPitchOverride,
                                              kNotCasting };

  return AnimVariableMasterGraphIndexes{ intVarIndexes, floatVarIndexes,
                                         boolVarIndexes };
}
