on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    env:
      buildDir: "${{ github.workspace }}/build/"
    steps:
      - uses: actions/checkout@master
        with:
          submodules: "recursive"
          fetch-depth: 0

      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Run CMake to generate project file and build the project
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: "CMakeLists.txt"
          buildDirectory: ${{ env.buildDir }}
          # This input tells run-cmake to consume the vcpkg.cmake toolchain file set by run-vcpkg.
          useVcpkgToolchainFile: true
          buildWithCMake: true
          buildWithCMakeArgs: "--config Release"
      - name: Use dev_service to pack everything into a dist directory
        working-directory: ./tools/dev_service
        run: npm run pack
      - name: Create an archive
        shell: bash
        run: |
          mkdir ./builds
          7z a -t7z -mx=9 ./builds/skyrim-platform-$(git describe --tags).7z ./tools/dev_service/dist/*
      - run: ls .
      - run: ls ./tools/dev_service/dist
      - uses: shallwefootball/s3-upload-action@master
        if: ${{ github.event_name == 'push' }}
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: "skyrim-platform-builds"
          source_dir: "./builds"
          destination_dir: ""
