# run_integration_test.cmake
#
# Runs a single integration JS test inside skymp5-server.
#
# Required variables (pass via -D):
#   TEST_SCRIPT  — absolute path to the test .js file
#   SERVER_DIR   — absolute path to the server directory (build/dist/server)
#
# Optional variables:
#   TEST_DB_DIR  — absolute path to a satellite folder with initial changeForms DB

# 0. Reset server-settings.json from the authoritative merged copy and apply
#    any test-specific patch, using node to handle JSON properly.
execute_process(
  COMMAND node -e "
    const fs = require('fs');
    const base = JSON.parse(fs.readFileSync('${SERVER_SETTINGS_BASE_JSON}', 'utf8'));
    const patch = '${TEST_SETTINGS_JSON}' !== ''
      ? JSON.parse(fs.readFileSync('${TEST_SETTINGS_JSON}', 'utf8'))
      : {};
    const result = Object.assign({}, base, patch);
    fs.writeFileSync('${SERVER_DIR}/server-settings.json', JSON.stringify(result, null, 2));
  "
  WORKING_DIRECTORY "${SERVER_DIR}"
  RESULT_VARIABLE _settings_res
)
if(NOT "${_settings_res}" STREQUAL "0")
  message(FATAL_ERROR "Failed to prepare server-settings.json")
endif()

# 1. Clean changeForms from previous runs
set(CHANGE_FORMS_DIR "${SERVER_DIR}/world/changeForms")
if(EXISTS "${CHANGE_FORMS_DIR}")
  file(REMOVE_RECURSE "${CHANGE_FORMS_DIR}")
endif()

# 2. If a satellite DB folder is provided, copy it into changeForms
if(TEST_DB_DIR AND EXISTS "${TEST_DB_DIR}")
  file(COPY "${TEST_DB_DIR}/" DESTINATION "${CHANGE_FORMS_DIR}")
endif()

# 3. Copy the test script as gamemode.js
file(COPY "${TEST_SCRIPT}" DESTINATION "${SERVER_DIR}")
get_filename_component(TEST_FILENAME "${TEST_SCRIPT}" NAME)
file(RENAME "${SERVER_DIR}/${TEST_FILENAME}" "${SERVER_DIR}/gamemode.js")

# 4. Run the server
execute_process(
  COMMAND node dist_back/skymp5-server.js
  WORKING_DIRECTORY "${SERVER_DIR}"
  TIMEOUT 60
  RESULT_VARIABLE res
  OUTPUT_VARIABLE out
  ERROR_VARIABLE err
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_STRIP_TRAILING_WHITESPACE
)

message("${out}")
message("${err}")

# 5. Clean up runtime artifacts generated by the server
foreach(_artifact
  "${SERVER_DIR}/server-settings-dump.json"
  "${SERVER_DIR}/server-settings-merged.json"
  "${SERVER_DIR}/data/manifest.json"
)
  if(EXISTS "${_artifact}")
    file(REMOVE "${_artifact}")
  endif()
endforeach()

# 6. Check result
if(NOT "${res}" STREQUAL "0")
  message(FATAL_ERROR "Integration test failed with exit code: ${res}")
endif()

if(NOT "${out}" MATCHES "Test passed!")
  message(FATAL_ERROR "Integration test did not print 'Test passed!' — server likely crashed before gamemode finished.\nstdout:\n${out}\nstderr:\n${err}")
endif()
