name: Deploy

on:
    workflow_dispatch:
        inputs:
            action:
                description: 'Action'
                required: true
                type: choice
                options:
                    - 'deploy'
                    - 'restart'
                    - 'stop'
                default: 'restart'
            branch:
                description: 'Branch, meaning server instance'
                required: true
                type: choice
                options:
                    - 'sweetpie'
                    - 'indev'
                    - 'indev-imp'
                default: 'indev'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Trigger server deploy job
            env:
              GH_TOKEN: ${{ secrets.SKYMP5_INSTALLER_REPOSITORY_DISPATCH_PAT }}
            run: |
              gh workflow run server-build-deploy-1-5.yml --repo skyrim-multiplayer/skymp5-installer-v2 \
                -f action='${{ inputs.action }}' \
                -f server_name='${{ inputs.branch }}' \
                -f real_triggering_actor='${{ github.triggering_actor }}' \
                ;
