on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: "recursive"
          fetch-depth: 0
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - run: docker build --tag skymp5-server .
      - run: docker run skymp5-server npm run test-prod
      - name: Push to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-3
          local-image: skymp5-server
          image: skymp5-server:$GITHUB_SHA
