name: Deploy Gamemode

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch, meaning server instance'
        required: true
        type: choice
        options:
          - 'sweetpie'
          - 'indev'
          - 'indev-imp'
        default: 'indev'

jobs:
  deploy_gamemode:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger gamemode deploy job
        env:
          GH_TOKEN: ${{ secrets.SKYMP5_INSTALLER_REPOSITORY_DISPATCH_PAT }}
        run: |
          gh workflow run server-build-deploy-1-5.yml --repo skyrim-multiplayer/skymp5-installer-v2 \
            -f action='deploy_gamemode' \
            -f server_name='${{ inputs.branch }}' \
            -f real_triggering_actor='${{ github.triggering_actor }}' \
            ;
