name: Deploy

on:
    workflow_dispatch:
        inputs:
            action:
                description: 'Action'
                required: true
                type: choice
                options:
                    - 'deploy'
                    - 'restart'
                    - 'stop'
                default: 'restart'
            branch:
                description: 'Branch, meaning server instance'
                required: true
                type: choice
                options:
                    - 'sweetpie'
                    - 'indev'
                default: 'indev'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Deploy the server
            uses: peter-evans/repository-dispatch@v2
            with:
              token: ${{ secrets.SKYMP5_INSTALLER_REPOSITORY_DISPATCH_PAT }}
              repository: skyrim-multiplayer/skymp
              event-type: 'deploy'
              client-payload: |
                {
                  "ref": "refs/heads/master",
                  "inputs": {
                    "action": "${{ inputs.action }}",
                    "server_name": "${{ inputs.branch }}"
                  }
                }
          # TODO: callback?
