name: Formatting check
on: [push, pull_request]
jobs:
    formatting-check:
        name: Formatting Check
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0

          - name: Run linters via JS
            run: |
              cd "${{ github.workspace }}/misc/git-hooks" && yarn
              if [ "${{ github.event_name }}" = "pull_request" ]; then
                node ./linter.js --lint --pr-diff origin/${{ github.event.pull_request.base.ref }} --no-path --mode gha
              else
                node ./linter.js --lint --pr-diff origin/${{ github.event.repository.default_branch }} --no-path --mode gha
              fi
