name: PR Comment Trigger
on:
  issue_comment:
    types: [created]
jobs:
    issue-comment-reformat:
        name: Formatting Check
        runs-on: ubuntu-latest
        if: contains(github.event.comment.body, '/reformat')
          - name: Checkout
            uses: actions/checkout@v2
          - name: Run Action
          - name: Ensure files use LF line endings instead of CRLF
            uses: erclu/check-crlf@v1
          - uses: DoozyX/clang-format-lint-action@v0.14
            with:
              source: '.'
              exclude: './skyrim-platform/src/third_party'
              extensions: 'h,cpp,hpp'
              clangFormatVersion: 12
              inplace: True
          - uses: EndBug/add-and-commit@v9
            with:
              default_author: github_actor
              message: 'Committing clang-format changes'
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
