name: PR Docker

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.0
          with:
            access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: 'true'
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - run: docker build -t skymp:test .