name: PR Windows Skyrim AE Indev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'
  VCPKG_FEATURE_FLAGS: 'manifests'

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: 'true'
      - uses: ./.github/actions/pr_base
        with:
          DESCRIPTION: 'Skyrim Anniversary Edition (1.6) - Indev'
          SKYRIM_SE_FLAG: OFF
          SP_NEXUS_ARTIFACT_NAME: nope
          DEPLOY_BRANCH: "indev"
          DIST_ARTIFACT_NAME: dist-indev
          SERVER_DIST_ARTIFACT_NAME: server-dist-indev
          SKYMP5_PATCHES_PAT: ${{ secrets.SKYMP5_PATCHES_PAT }}
